### ISSUE TITLE
Content Languages Activation

### ISSUE THREAD

**Issue by seancarew** [JoomFish/joomfish-2.5#128] opened 2013-01-21 17:57 UTC
In the backend, at Content Language -

When I try to 'activate' then 'apply' a new 'content' language, I get this error...

'An error occured while saving your languages.'

Trying to just 'save' gives me this error:

'Error Saving Languages:Array'

I was able to activate 1 additional language just after installation. None since.

However, I am able to install more content languages... unable to activate any additional languages.
## 

System Information

Database Version 5.1.61-log
Database Collation utf8_general_ci
PHP Version 5.3.14
Web Server Apache/2.2
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 2.5.8 Stable [ Ember ] 8-November-2012 14:00 GMT
Joomla! Platform Version Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT

Also, I have noticed the default language appears twice in the joomla content language interface/

**Comment by klas** [comment] 2013-01-21 21:02
Duplicate of #129

**Closed as completed by klas** 2013-01-21 21:02 UTC
