### ISSUE TITLE
Router problem with Joomla SEF enabled?

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#28] opened 2012-02-10 14:12 UTC
In short: I this error in the frontend when viewing an article and then changing the language when Joomla SEF is enabled (no error when Joomla SEF is disabled).
_Error: 500, You may not be able to visit this page because of: (etc....)
View not found [name, type, prefix]: 19sample-data-articles, html, contentView_

**System**
- Joomla 2.5.1 - with sample content, english (en-GB) as default language and second language dutch (nl-NL)
- Debug System = Yes
- Error Reporting = Maximum
- Search Engine Friendly URLs = Yes
- Joomfish 2.5 alpha for Joomla 2.5 (latest commit was a4aaa16643)
- Database MySQL 5.1.3
- PHP 5.2.9
- Apache on windows (Xampp)
- User agent Mozilla/5.0 (Firefox 3.6.26)

**Test scenario**
- Translate content article Beginners: Backend > Components > JoomFish > Translation > Languages = Dutch & Content elements = Contents > Click article Beginners (translated only Title, Alias and Article Text) and checkmark publishe > Save. 
  Note: The rest of the values is not copied.
- Frontend Home in default english (en-GB)
- Change the language to the second language (nl-NL) in the language module (changing this back and forth is not a problem)
- click translated Beginners article title 
  Takes me to:
  /JOOMLAROOT/index.php/nl/using-joomla/extensions/components/content-component/article-category-list/75-beginners-nl
- Change the language to the first language in the language module (en-GB)
  Takes me to:
  URL: /JOOMLAROOT/index.php/en/component/content/19-sample-data-articles/joomla/75-beginners-nl?Itemid=260, with an error:
  --> _seeing /component/ in a URL never seems to be a good thing :(_
  --> Error: 500, You may not be able to visit this page because of: (etc....)
  **View not found [name, type, prefix]: 19sample-data-articles, html, contentView**
  Call stack
  #   Function    Location
  1   JSite->dispatch()   D:\website_spul\xampp\htdocs\joomla_development\joomla25\index.php:42
  2   JComponentHelper::renderComponent()     D:\website_spul\xampp\htdocs\joomla_development\joomla25\includes\application.php:187
  3   JComponentHelper::executeComponent()    D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\application\component\helper.php:357
  4   require_once()  D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\application\component\helper.php:388
  5   JController->execute()  D:\website_spul\xampp\htdocs\joomla_development\joomla25\components\com_content\content.php:18
  6   ContentController->display()    D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\application\component\controller.php:754
  7   JController->display()  D:\website_spul\xampp\htdocs\joomla_development\joomla25\components\com_content\controller.php:77
  8   JController->getView()  D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\application\component\controller.php:671
  9   JError::raiseError()    D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\application\component\controller.php:896
  10  JError::raise()     D:\website_spul\xampp\htdocs\joomla_development\joomla25\libraries\joomla\error\error.php:251

If I go from the Home when the language is set to en-GB and then to the Beginners article the URL is:
/JOOMLAROOT/index.php/en/using-joomla/extensions/components/content-component/article-category-list/8-beginners which is different

**With Joomla SEF disabled (setting Search Engine Friendly URLs = Yes) it works fine.**

Saving the translation with all options/items/fields copied and then saving doesn't change the behaviour.

**Comment by klas** [comment] 2012-02-12 11:19
Confirmed,  seems the problem is in a module, joomla links work fine, only direct switching with module does not

**Comment by quodo** [comment] 2012-02-13 10:00
Yes, now I can switch languages for an article with the "JF Language Selection" module when Joomla SEF is enabled!

**Comment by klas** [comment] 2012-02-13 10:16
Thnx, closing then :)

**Closed as completed by klas** 2012-02-13 10:16 UTC
