### ISSUE TITLE
ERROR_SAVING_TRANSLATION without telling the user what the error is

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#11] opened 2012-01-13 14:54 UTC
On different errors when saving translations JoomFish does not report to the user what the problem is. Two examples on J!1.7.3 with dutch (nl-NL) as second language and with the current jf-future (how would I reference the current git version?).

**Example duplicate alias in menu**
When you try to save a translation with an alias that already exists (e.g. the alias of the translation is the same as the alias of the original language) you'll get a blue "ERROR_SAVING_TRANSLATION" message.

Test
- JoomFish Translation menu
- choose Languages = Dutch (or your 2nd language)
- choose Content elements = Menus
- edit any menu item, but keep the translation alias the same as the original alias
- click save (& close)
  Result
- Blue "ERROR_SAVING_TRANSLATION" message, user has no clue what the problem is.

Function store in class JTableMenu (extends JTableNested) (file /JOOMLAROOT/libraries/joomla/database/table/menu.php (J!1.7.3)) starts with

```
        if ($table->load(array('alias'=>$this->alias, 'parent_id'=>$this->parent_id, 'client_id'=>$this->client_id)) && ($table->id != $this->id || $this->id==0)) {
            if ($this->menutype==$table->menutype) {
                $this->setError(JText::_('JLIB_DATABASE_ERROR_MENU_UNIQUE_ALIAS'));
            }
            else {
                $this->setError(JText::_('JLIB_DATABASE_ERROR_MENU_UNIQUE_ALIAS_ROOT'));
            }
            return false;
        }
```

which returns false in case of an existing alias, but JoomFish doesn't seem to show the error JLIB_DATABASE_ERROR_MENU_UNIQUE_ALIAS?

**Example saving contents without intro text**
Similarly, if you try to save an article (contents) and don't have any introtext you'll get to (file /JOOMLAROOT/libraries/joomla/databas/table/content.php, lines 180-183 in J!1.7.3)

```
        if (trim($this->introtext) == '' && trim($this->fulltext) == '') {
            $this->setError(JText::_('JGLOBAL_ARTICLE_MUST_HAVE_TEXT'));
            return false;
        }
```

Again, this JGLOBAL_ARTICLE_MUST_HAVE_TEXT-error is not shown to the user.

**Comment by akempkens** [comment] 2012-01-15 11:34
I realized this same issue in 2.2 and fixed it in the jf-core code. The issue is related to the fact that only the last error message is sent to the front-end. As the language class is separated in two classes it happens that sometimes that a second empty message is added to the cue. I will try to apply the patch I had with the 2.2.3 code.

**Comment by klas** [comment] 2012-01-24 12:01
Was auto closed by github , reopening for testing

**Comment by quodo** [comment] 2012-01-30 15:32
Works for me, on J!2.5.0.
- Default language en-GB
- Second language nl-NL (dutch). 
- Joomla 2.5.0 (and 1.7.3 as well). 
- JoomFish from GitHub from today: jan. 30, 2012 
  (should I and/or how can I indicate exactly which 'snapshot' of the Github repository I used?)

**Tested**: Dutch + Contents as Content Element (this used to go wrong)
1) Translation having same alias as original: 
redirect with red "Another article from this category has the same alias"-message and blue ERROR_SAVING_TRANSLATION"-message
2) Translation with not Article Text: 
redirect with red "Article must have some content."-message and blue "ERROR_SAVING_TRANSLATION"-message

**Comment by klas** [comment] 2012-01-30 20:34
ok closing

**Comment by klas** [comment] 2012-01-30 20:34
and thnx for testing :)

**Closed as completed by klas** 2012-01-30 20:34 UTC
