### ISSUE TITLE
Alpha2 quetions

### ISSUE THREAD

**Issue by ghost** [JoomFish/joomfish-2.5#91] opened 2012-07-11 07:15 UTC
Hello,

I have several questions about joomfish alpha 2:
- Is it normal that when I translate an article, a module, ... there is created a new article / module containing the translation?
- If you want to change the homepage link, you can not make it point to new article ( in french > default) and we get: "Save the Following failed with error: The Language menu item for this parameter must Be set to 'All'. At least one menu item Default Language must have set to All, Even If the site is multilingual. "

Thank you for your time

**Comment by klas** [comment] 2012-07-11 09:04
Hi,
- this is perfectly normal as native translations are used for core extensions
- this is a duplicate of issue $84

**Closed as completed by klas** 2012-07-11 09:04 UTC
